---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jakub Wilkosz.
--- DateTime: 14/09/2019 13:53
---
local SpellbookView = require("actors.spellbook.SpellbookView")
local Spell = require("actors.spell.Spell")
local isColliding = require("utils.collisions").isColliding
local Spellbook = {}
local spells = {}
Spellbook.__index = Spellbook

function Spellbook.new(spelllist, view)
    return setmetatable({
        spells = spelllist,
        view = view
    },
        Spellbook
    )
end

function Spellbook.load(spellslist)
    local spelllist = {}
    for k, spell in pairs(spellslist) do
        table.insert(spelllist, Spell.load(spell))
    end

    local view = SpellbookView.new(spelllist)

    return Spellbook.new(spelllist, view)
end

function Spellbook:draw()
    self.view:draw()
end

function Spellbook:getUsedSpell(x, y)
    for k, spell in pairs(self.spells) do
        if isColliding({x=x,y=y}, spell.view:getBoundingBox()) then
            return spell
        end
    end
    return nil
end



return Spellbook