---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jakub Wilkosz.
--- DateTime: 14/09/2019 13:54
---

local SpellbookView = {}

SpellbookView.__index = SpellbookView

function SpellbookView.new(spells)
    print(table.getn(spells))
    return setmetatable(
        {
            spells = spells
        },
        SpellbookView
    )
end

function SpellbookView:draw()
    print(table.getn(self.spells))
    for k, spell in pairs(self.spells) do
        print(k)
        spell.view:draw()
    end
end

return SpellbookView