---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jakub Wilkosz.
--- DateTime: 14/09/2019 13:15
---

local ImageRenderer = require("rendering.ImageRenderer")

local SpellView = {}
SpellView.__index = SpellView

function SpellView.new(x, y, width, height, image, rotation, xOffset, yOffset)
    return setmetatable(
            {
                renderer = ImageRenderer.new(
                        image,
                        x,
                        y,
                        rotation,
                        width / image:getWidth(),
                        height / image:getHeight(),
                        xOffset,
                        yOffset
                ),
                width = width,
                height = height
            },
            SpellView
    )
end

function SpellView:draw()
    self.renderer:draw()
end

function SpellView:getBoundingBox()
    return {
        x = self.renderer.x,
        y = self.renderer.y,
        width = self.width,
        height = self.height
    }
end

return SpellView